name: Application Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'scripts/README.md/k8s'

jobs:

  ci:
    uses: shravansonone/RTB-GH-Action/.github/workflows/ci.yml@main
    secrets: inherit

  cd:
    needs: ci
    uses: shravansonone/RTB-GH-Action/.github/workflows/cd.yaml@main
    secrets: inherit
    with:
      image_tag: ${{ needs.ci.outputs.commit_id }}
