name: Application Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'scripts/README.md'

jobs:

  ci:
    uses: shravansonone/RTB-GH-Action/.github/workflows/ci.yml@main

  cd:
    needs: ci
    uses: shravansonone/RTB-GH-Action/.github/workflows/cd.yml@main
